{
	"Service": "/BasicMDKApp/Services/MDPAppService.service",
	"DefiningRequests": [{
		"Name": "Customers",
		"Query": "Customers"
	}],
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnSuccess": "/BasicMDKApp/Actions/Service/SyncSuccessMessage.action",
	"OnFailure": "/BasicMDKApp/Actions/Service/SyncFailureMessage.action"
}